import json
import boto3
import logging
import time
from datetime import datetime
from botocore.exceptions import ClientError

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Lambda function to fetch AWS Service Quotas for Bedrock models and publish as CloudWatch metrics
# 
# Expected event structure:
# - For Custom Resource events: event['ResourceProperties']['models']
# - For EventBridge events: event['models']
# 
# Each model object should contain:
# - modelId: Full model ID with endpoint prefix (e.g., 'us.amazon.nova-micro-v1:0')
# - tokenQuotaCode: AWS Service Quota code for token limits (e.g., 'L-DC7FF66C')
# - requestQuotaCode: AWS Service Quota code for request limits (e.g., 'L-3F110E0F')
#
# The data structure is generated by the CDK stack using the registry-based approach
# from lib/bedrock-registries.ts

# Global cache for all quotas (persists across Lambda invocations)
all_quotas_cache = None
cache_timestamp = None
CACHE_TTL_SECONDS = 3600  # 1 hour cache

# Initialize clients outside handler for connection reuse
sq_client = boto3.client('service-quotas')
cw_client = boto3.client('cloudwatch')

def get_all_quotas(service_code='bedrock', max_retries=5):
    """Fetch all quotas for a service in one call and cache them."""
    global all_quotas_cache, cache_timestamp
    
    current_time = time.time()
    
    # Check cache first
    if all_quotas_cache and cache_timestamp and (current_time - cache_timestamp) < CACHE_TTL_SECONDS:
        logger.info(f'Using cached quotas ({len(all_quotas_cache)} quotas)')
        return all_quotas_cache
    
    # Fetch all quotas with pagination
    logger.info(f'Fetching all quotas for service: {service_code}')
    quotas = {}
    
    for attempt in range(max_retries):
        try:
            paginator = sq_client.get_paginator('list_service_quotas')
            page_iterator = paginator.paginate(ServiceCode=service_code)
            
            for page in page_iterator:
                for quota in page.get('Quotas', []):
                    quota_code = quota.get('QuotaCode')
                    quota_value = quota.get('Value')
                    if quota_code and quota_value is not None:
                        quotas[quota_code] = quota_value
            
            # Update cache
            all_quotas_cache = quotas
            cache_timestamp = current_time
            
            logger.info(f'Fetched {len(quotas)} quotas from API')
            return quotas
            
        except ClientError as error:
            if error.response['Error']['Code'] == 'TooManyRequestsException':
                if attempt < max_retries - 1:
                    wait_time = min(30, (2 ** attempt) + (time.time() % 1))
                    logger.warning(f'Rate limited, retrying in {wait_time:.2f}s (attempt {attempt + 1}/{max_retries})')
                    time.sleep(wait_time)
                    continue
                else:
                    raise Exception(f'Max retries exceeded fetching all quotas after rate limiting')
            else:
                raise Exception(f'Error fetching quotas: {error}')
    
    raise Exception(f'Failed to fetch quotas after {max_retries} attempts')

def handler(event, context):
    logger.info(f'Event: {json.dumps(event)}')
    
    # Determine event type
    is_custom_resource = 'RequestType' in event
    
    # Handle Delete events for Custom Resources
    if is_custom_resource and event['RequestType'] == 'Delete':
        return {
            'PhysicalResourceId': event.get('PhysicalResourceId', 'initial-quota-fetch'),
            'Data': {}
        }
    
    # Get models from the appropriate location
    models = event['ResourceProperties'].get('models', []) if is_custom_resource else event.get('models', [])
    
    if not models:
        logger.warning('No models provided in event')
        if is_custom_resource:
            return {
                'PhysicalResourceId': 'initial-quota-fetch',
                'Data': {}
            }
        else:
            return {'statusCode': 200, 'body': 'No models to process'}
    
    logger.info(f'Fetching quotas for {len(models)} models')
    all_quotas = get_all_quotas('bedrock')
    
    # Track processing statistics
    processed_models = 0
    successful_token_quotas = 0
    successful_request_quotas = 0
    
    # Publish metrics for all models
    for model in models:
        # Validate model structure
        if not isinstance(model, dict):
            logger.error(f'Invalid model data structure: {model}')
            continue
            
        model_id = model.get('modelId')
        token_quota_code = model.get('tokenQuotaCode')
        request_quota_code = model.get('requestQuotaCode')
        
        if not model_id:
            logger.error(f'Missing modelId in model data: {model}')
            continue
            
        processed_models += 1
        
        # Process token quota
        if token_quota_code:
            token_quota = all_quotas.get(token_quota_code)
            if token_quota:
                publish_metric(model_id, 'token', token_quota)
                successful_token_quotas += 1
            else:
                logger.warning(f"Token quota code {token_quota_code} not found for {model_id}")
        else:
            logger.warning(f"No token quota code provided for {model_id}")
        
        # Process request quota
        if request_quota_code:
            request_quota = all_quotas.get(request_quota_code)
            if request_quota:
                publish_metric(model_id, 'request', request_quota)
                successful_request_quotas += 1
            else:
                logger.warning(f"Request quota code {request_quota_code} not found for {model_id}")
        else:
            logger.warning(f"No request quota code provided for {model_id}")
    
    # Log processing summary
    logger.info(f'Processing complete: {processed_models} models processed, '
                f'{successful_token_quotas} token quotas published, '
                f'{successful_request_quotas} request quotas published')
    
    # Return appropriate response based on event type
    if is_custom_resource:
        return {
            'PhysicalResourceId': 'initial-quota-fetch',
            'Data': {
                'ProcessedModels': processed_models,
                'SuccessfulTokenQuotas': successful_token_quotas,
                'SuccessfulRequestQuotas': successful_request_quotas
            }
        }
    else:
        return {
            'statusCode': 200, 
            'body': json.dumps({
                'message': f'Quotas refreshed for {processed_models} models',
                'processedModels': processed_models,
                'successfulTokenQuotas': successful_token_quotas,
                'successfulRequestQuotas': successful_request_quotas
            })
        }

def publish_metric(model_id, quota_type, quota_value):
    metric_name = 'TokenQuota' if quota_type == 'token' else 'RequestQuota'
    cw_client.put_metric_data(
        Namespace='Bedrock/Quotas',
        MetricData=[
            {
                'MetricName': metric_name,
                'Dimensions': [
                    {
                        'Name': 'ModelId',
                        'Value': model_id
                    }
                ],
                'Value': quota_value,
                'Unit': 'None',
                'Timestamp': datetime.utcnow()
            }
        ]
    )
    logger.info(f'Published {quota_type} quota for {model_id}: {quota_value}')